# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lemon3 < Formula
  desc "lemon3 is a filesharing system using Farcaster and IPFS."
  homepage "https://github.com/vrypan/lemon3"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/lemon3/releases/download/v0.4.0/lemon3_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "1f931d098ea708b64dfb4999ffc57184e4a530036fc2c70c802db6e65ef0cdf6"

      def install
        bin.install "lemon3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/lemon3/releases/download/v0.4.0/lemon3_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "f0092db9405a2ad0b822e60fc988b4c984c882e585d9c7f020db281bf069c381"

      def install
        bin.install "lemon3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/lemon3/releases/download/v0.4.0/lemon3_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "5153c7e0754f8534d4574186fd452e3e24836d57bf08a0b5f5db1beff0127f6d"
      def install
        bin.install "lemon3"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/lemon3/releases/download/v0.4.0/lemon3_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "3e565919cf3c82236656a69adf6321e022f12fc02d37adc0c9a9c1a041d0ad66"
      def install
        bin.install "lemon3"
      end
    end
  end

  def caveats
    <<~EOS
      lemon3 --help
    EOS
  end

  test do
    system "#{bin}/lemon3 version"
  end
end
