# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lemon3 < Formula
  desc "lemon3 is a filesharing system using Farcaster and IPFS."
  homepage "https://github.com/vrypan/lemon3"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/lemon3/releases/download/v0.2.1/lemon3_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "bb9f8d26c0134595b9268bae96b4c79d74b0535676040239dfd14f44afe25bc1"

      def install
        bin.install "lemon3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/lemon3/releases/download/v0.2.1/lemon3_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "bf9512528deb7c3adc772f76e59216bf64335e77b179f1cd76ba6159c4efbcfc"

      def install
        bin.install "lemon3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/lemon3/releases/download/v0.2.1/lemon3_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "65c4dea6fd6df0c6bbad898ca8fc39795e31b1209fb93b35f24c0fd747d18fcb"
      def install
        bin.install "lemon3"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/lemon3/releases/download/v0.2.1/lemon3_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "9103f83bbae5a031f90836047679c0569a0d644ee1b1ac6b636c020bb51af5b9"
      def install
        bin.install "lemon3"
      end
    end
  end

  def caveats
    <<~EOS
      lemon3 --help
    EOS
  end

  test do
    system "#{bin}/lemon3 version"
  end
end
